SCM:
  warmth_pairs: "Integrating_SCM_SD/bin/doc/SCM_warmth_paris.csv" # system
  competent_pairs: "Integrating_SCM_SD/bin/doc/SCM_competent_pairs.csv" # system
  All_pairs: "Integrating_SCM_SD/bin/doc/SCM_all_pairs.csv"
SD:
  activity: "Integrating_SCM_SD/bin/doc/osgood_01_activity.csv"
  evaluation: "Integrating_SCM_SD/bin/doc/osgood_01_evaluation.csv"
  potency: "Integrating_SCM_SD/bin/doc/osgood_01_potency.csv"
  

Jenkins:
  pairs: "Integrating_SCM_SD/bin/doc/Jenkins_pairs.csv"

Osgood:
  50_pairs: "Integrating_SCM_SD/bin/doc/osgood_50.csv"

Trust:
  20_paris: "Integrating_SCM_SD/bin/doc/trustworthiness.csv"

Reduction:
  SCM_warmth: "Integrating_SCM_SD/bin/doc/reduction_pairs/scm_warmth.csv"
  SCM_competent: "Integrating_SCM_SD/bin/doc/reduction_pairs/scm_competent.csv"
  Osgood_evaluation: "Integrating_SCM_SD/bin/doc/reduction_pairs/osgood_evaluation.csv"
  Osgood_potency: "Integrating_SCM_SD/bin/doc/reduction_pairs/osgood_potency.csv"
  Osgood_activity: "Integrating_SCM_SD/bin/doc/reduction_pairs/osgood_activity.csv"
  Trustworthy: "Integrating_SCM_SD/bin/doc/reduction_pairs/trustworthy.csv"