SCM:
  warmth_pairs: "Integrating_SCM_SD/bin/doc/SCM_warmth_paris.csv" # system
  competent_pairs: "Integrating_SCM_SD/bin/doc/SCM_competent_pairs.csv" # system


SD:
  evaluation: "Integrating_SCM_SD/bin/doc/SD_evaluation_pairs.csv"
  potency: "Integrating_SCM_SD/bin/doc/SD_potency_pairs.csv"
  activity:

Jenkins:
  pairs: "Integrating_SCM_SD/bin/doc/Jenkins_pairs.csv"


