SCM:
  warmth_pairs: "Integrating_SCM_SD/bin/doc/SCM_warmth_paris.csv" # system
  competent_pairs: "Integrating_SCM_SD/bin/doc/SCM_competent_pairs.csv" # system


SD:
  activity: "Integrating_SCM_SD/bin/doc/osgood_01_activity.csv"
  evaluation: "Integrating_SCM_SD/bin/doc/osgood_01_evaluation.csv"
  potency: "Integrating_SCM_SD/bin/doc/osgood_01_potency.csv"
  

Jenkins:
  pairs: "Integrating_SCM_SD/bin/doc/Jenkins_pairs.csv"


