SCM:
  warmth_pairs: "Integrating_SCM_SD/bin/doc/original_pairs/SCM_warmth_paris.csv" # system
  competent_pairs: "Integrating_SCM_SD/bin/doc/original_pairs/SCM_competent_pairs.csv" # system
  All_pairs: "Integrating_SCM_SD/bin/doc/SCM_all_pairs.csv"
  warmth_pairs_contrusting: "Integrating_SCM_SD/bin/doc/original_pairs/SCM_warmth_contrusting.csv"
  competent_pairs_contrusting: "Integrating_SCM_SD/bin/doc/original_pairs/SCM_competent_contrusting.csv"
  scm_competent_mce: "Integrating_SCM_SD/bin/output/contrusting_pairs_mce/scm_competent_mce"
  scm_warmth_mce: "Integrating_SCM_SD/bin/output/contrusting_pairs_mce/scm_warm_mce"
SD:
  activity: "Integrating_SCM_SD/bin/doc/original_pairs/osgood_activity.csv"
  evaluation: "Integrating_SCM_SD/bin/doc/original_pairs/osgood_evaluation.csv"
  potency: "Integrating_SCM_SD/bin/doc/original_pairs/osgood_potency.csv"
  

Jenkins:
  pairs: "Integrating_SCM_SD/bin/doc/Jenkins_pairs.csv"

Osgood:
  50_pairs: "Integrating_SCM_SD/bin/doc/osgood_50.csv"

Trust:
  20_paris: "Integrating_SCM_SD/bin/doc/original_pairs/trustworthiness.csv"

Reduction:
  SCM_warmth: "Integrating_SCM_SD/bin/doc/reduction_pairs/scm_warmth.csv"
  SCM_competent: "Integrating_SCM_SD/bin/doc/reduction_pairs/scm_competent.csv"
  Osgood_evaluation: "Integrating_SCM_SD/bin/doc/reduction_pairs/osgood_evaluation.csv"
  Osgood_potency: "Integrating_SCM_SD/bin/doc/reduction_pairs/osgood_potency.csv"
  Osgood_activity: "Integrating_SCM_SD/bin/doc/reduction_pairs/osgood_activity.csv"
  Trustworthy: "Integrating_SCM_SD/bin/doc/reduction_pairs/trustworthy.csv"

Dir:
  original_pairs: "Integrating_SCM_SD/bin/doc/original_pairs/"
  reduction_pairs: "Integrating_SCM_SD/bin/doc/reduction_pairs/"

GPT:
  warmth_pairs: "Integrating_SCM_SD/bin/doc/gpt_pairs/gpt_warmth.csv"
  competent_pairs: "Integrating_SCM_SD/bin/doc/gpt_pairs/gpt_competent.csv"

Mixed:
  warmth_pairs: "Integrating_SCM_SD/bin/doc/final_pairs/mixed_warmth.csv"
  competent_pairs: "Integrating_SCM_SD/bin/doc/final_pairs/mixed_competent.csv"
  
Model_path:
  mce: "word_embeddings/mce_vectors.txt"
  google_news: "word_embeddings/GoogleNews-vectors-negative300.bin"
  glove: "word_embeddings/glove.840B.300d.txt"
  fasttext: "word_embeddings/crawl-300d-2M-subword.bin"