# the seed words for each dimension
word_pairs:
  warmth_pairs: "Integrating_SCM_SD/bin/doc/seed_words/warmth.csv"
  competent_pairs: "Integrating_SCM_SD/bin/doc/seed_words/competence.csv"
  communion_pairs: "Integrating_SCM_SD/bin/doc/seed_words/communion.csv"
  agency_pairs: "Integrating_SCM_SD/bin/doc/seed_words/agency.csv"


# the contrusting pairs for each dimension
contrasting_pairs:
  # constructed by the original pairs
  warmth_pairs: "Integrating_SCM_SD/bin/doc/contrasting_pairs/warmth_contrasting.csv"
  competent_pairs: "Integrating_SCM_SD/bin/doc/contrasting_pairs/competence_contrasting.csv"
  communion_pairs: "Integrating_SCM_SD/bin/doc/contrasting_pairs/communion_contrasting.csv"
  agency_pairs: "Integrating_SCM_SD/bin/doc/contrasting_pairs/agency_contrasting.csv"

  # Osgood's original contrasting pairs
  evaluation_pairs: "Integrating_SCM_SD/bin/doc/contrasting_pairs/evaluation_contrasting.csv"
  potency_pairs: "Integrating_SCM_SD/bin/doc/contrasting_pairs/potency_contrasting.csv"
  activity_pairs: "Integrating_SCM_SD/bin/doc/contrasting_pairs/activity_contrasting.csv"

indirect_pairs:
  warmth_pairs: "Integrating_SCM_SD/bin/doc/indirect_pairs/warmth_indirect.csv"
  competent_pairs: "Integrating_SCM_SD/bin/doc/indirect_pairs/competence_indirect.csv"
  communion_pairs: "Integrating_SCM_SD/bin/doc/indirect_pairs/communion_indirect.csv"
  agency_pairs: "Integrating_SCM_SD/bin/doc/indirect_pairs/agency_indirect.csv"

# the path for drawing the figure
pics:
  dimensionsVectors_googlenews: "Integrating_SCM_SD/bin/doc/output/dimensions.npy"
  dimensionsVectors_fasttext: "Integrating_SCM_SD/bin/doc/output/dimensions_fasttext.npy"
  dimensionsVectors_indirect: "Integrating_SCM_SD/bin/output/dimensions_indirect_DPM.npy"
  heatmap: "Integrating_SCM_SD/bin/doc/output/heatmap.png"
  quadrant: "Integrating_SCM_SD/bin/doc/output/quadrant.png"

# model path
model_path:
  mce: "word_embeddings/mce_vectors.txt"
  google_news: "word_embeddings/GoogleNews-vectors-negative300.bin"
  glove: "word_embeddings/glove.840B.300d.txt"
  fasttext: "word_embeddings/crawl-300d-2M-subword.bin"

# the path for the output of the model
model_path_output:
  SCM_google_news: "word_embeddings/SCM_2D.bin"
  DPM_google_news: "word_embeddings/DPM_2D.bin"
  SD_google_news: "word_embeddings/SD_2D.bin"
  New2_google_news: "word_embeddings/New2_2D.bin"
  DPM_google_news_indirect: "word_embeddings/DPM_2D_indirect.bin"

dimensionsAll:
  allPairs: "Integrating_SCM_SD/bin/doc/output/all_data.pkl"

